# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 761a57eb35cf66cc81e1677e1d128e68a4aa89de4bbc63edee133029c11aa9478f714815fae80d7a8ece599215991c31fb0262138a5b26fcb097440f321b0e2c

test:
  secret_key_base: 609169d126ba569f4155b85b9ef0648d1d4581b38856142b9fce2e8798915a38b6d06a94c7ce4d8fd7df7e84e6d3bc990cd39ff736a0dc91c0221400343b659d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
